apiVersion: v1
kind: Pod
metadata:
  name: l1metml-pod-john
  labels:
    app: l1metml
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/jmduarte/l1metml:latest
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      limits:
        memory: 8Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 4Gi
        cpu: "1"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /l1metmlvol
      name: l1metmlvol
  restartPolicy: Never
  volumes:
    - name: l1metmlvol
      persistentVolumeClaim:
        claimName: l1metmlvol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - 1080Ti
